apiVersion: apps/v1
kind: Deployment
metadata:
 creationTimestamp: null
 labels:
  app: orders-ms
 name: orders-ms
spec:
 replicas: 1
 selector:
  matchLabels:
   app: orders-ms
 strategy: {}
 template:
  metadata:
   creationTimestamp: null
   labels:
    app: orders-ms
  spec:
   containers:
    - image: us-central1-docker.pkg.dev/microservices-store-425413/image-registry/order-ms
      name: order-ms
      env:
       - name: PORT
         value: '3000'
       - name: NATS_SERVERS
         value: 'nats://nats'
       - name: DATABASE_URL
         valueFrom:
          secretKeyRef:
           name: orders-secrets
           key: database_url
      resources: {}
status: {}
